services:
  postgres:
    image: postgres:17-alpine
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "resumeinsync"

volumes:
  postgres_data: